### PR TITLE
PATCH: allow SS5.0

### PR DESCRIPTION
**Pull request by sunnysideup**

### CODE REVIEW

**Review by shanholmes — APPROVED** [review]
This is a change that I made in my fork and was about to submit.

**Comment by shanholmes** [comment]
@sheadawson when you have a second could you review this one?

**Comment by NightJar** [comment]
The line should just be removed - framework depends on this, it is already part of the dependency graph. There is no reason for a direct dependency to be made.

**Comment by NightJar** [comment]
Thanks @sheadawson! ❤️

**Pull request closed without merging**
