### PR TITLE
Set correct casting for $ClassAttr and $TargetAttr

### PR DESCRIPTION
**Pull request by priyashantha**
This will fix the issue which class and target attributes wrongly processed.

### CODE REVIEW

**Comment by sheadawson** [comment]
@priyashantha Quotes are not added in the template. The strings returned in php are the attribute key and value. See https://github.com/sheadawson/silverstripe-linkable/blob/master/templates/Sheadawson/Linkable/Models/Link.ss. Unless I am missing something?

**Comment by priyashantha** [comment]
@sheadawson You're correct that the quotes are not added in the template manually for title and target attributes but when the template is rendered they are added automatically somehow (may be because of change in ss4)

So when I have called this in a template `$LinkObject.setCSSClass('left')` it output anchor tag like `<a href="/link" class="'left'">link title</a>` class in single quotes inside double quotes which is not correct. So that issue was fixed by the above update for me

**Comment by sheadawson** [comment]
@priyashantha ok not sure why that would be happening. Could be something in `Link::getClassAttr()` method

**Comment by michalkleiner** [comment]
SS4 changed a bit in terms of how it escapes stuff in templates which might be the cause of this. However, the fix won't be to remove the apostrophes from the string, rather then figuring out how to pass it differently to the template to make it work. I guess adding `.RAW` will fix that.

**Comment by priyashantha** [comment]
@michalkleiner You're correct that that was not the smartest/best solution. Just went with that because it solved the issue. Anyways, I'll have a dig in the framework and check I can find out something what's going on.

Btw, it's strage that the `.RAW` only fix class attribute but not target attribute. :(

**Comment by michalkleiner** [comment]
Ok, try removing all your changes from the template and set up casting in the model, similar to
```
private static $casting = [
    'getClassAttr' => 'HTMLFragment',
    'getTargetAttr' => 'HTMLFragment',
];
```

That should tell the template not to escape it at all and pass it as is.

**Comment by priyashantha** [comment]
@michalkleiner Yeah!! it did the trick. Thank you very much. Just needed it like:

```
private static $casting = [
    'ClassAttr' => 'HTMLFragment',
    'TargetAttr' => 'HTMLFragment',
];
```

@sheadawson Is this good to be merged now?

**Pull request merged**
