### PR TITLE
Dbfield link type

### PR DESCRIPTION
**Pull request by gorriecoe**
Added check for db Field in the link object or relationship to another
object

### CODE REVIEW

**Comment by gorriecoe** [comment]
Hi Shea,  If you could review and merge is as soon as possible that would be great.  I have a few projects that will need this including the one I'm working on.   Cheers

**Comment by gorriecoe** [comment]
Just to give you a general idea what I'm using it for.   I'm linking to a thirdparty site so I want the user to be able to enter the ID and have my code wrap it with the full link.

**Comment by sheadawson** [comment]
@gorriecoe I see, cool! Will merge into master for now, test and release myself when I get back in September. Cheers!

**Comment by martinduparc** [comment]
@gorriecoe 

I think this PR introduced a bug with `mailto` and `tel` links. 

On lines [325](https://github.com/sheadawson/silverstripe-linkable/blob/master/code/dataobjects/Link.php#L325) and [327](https://github.com/sheadawson/silverstripe-linkable/blob/master/code/dataobjects/Link.php#L327), the url containing the proper protocol is reset on line [330](https://github.com/sheadawson/silverstripe-linkable/blob/master/code/dataobjects/Link.php#L330)

**Comment by gorriecoe** [comment]
Thanks @martinduparc,  Yeah I missed some breaks in the switch.  #64 Should fix this.

**Pull request merged**
