### PR TITLE
Make SiteTree implementation optional with data extension

### PR DESCRIPTION
**Pull request by satrun77**
Hi there

Making the SiteTree implementation optional would make the module useful for application that only uses the framework module.

Thanks

### CODE REVIEW

**Comment by sheadawson** [comment]
Great stuff. Just a small suggestion before merge - can we use the [moduleexists](https://docs.silverstripe.org/en/3.1/developer_guides/configuration/configuration/) exclusionary rule to apply the LinkableSiteTreeExtension? ie. `moduleexists: 'cms'`. That way users do not have to add the extension manually, and upgrading to to this feature will be seamless

**Comment by satrun77** [comment]
I have updated the PR to use the moduleexists rule.

Cheers

**Comment by sheadawson** [comment]
Nice one, can you remove the instructions from the readme they aren't needed any more, then good to go :)

**Comment by satrun77** [comment]
That is true! PR updated.

Merry Xmas

**Pull request merged**
